#ifndef CONSTANTS_H
#define CONSTANTS_H

#define INITIAL_CAPACITY 64
#define MAX_LINE 256

#define DEFAULT_LABEL_VALUE 0
#define IGNORE_INSTR_EDIT_SINCE_NO_INSTRUCTIONS -1

#define DEFAULT_START_FREE_INDEX 0
#define INITIAL_SYMBOLS_COUNT 23
#define INITIAL_DESTS_COUNT 8
#define INITIAL_COMPS_COUNT 28
#define INITIAL_JUMPS_COUNT 8

#endif
